### ISSUE TITLE
Do you mind if there's a PAL version of this?

### ISSUE THREAD

**Issue by threecreepio** [pellsson/smb#29]
Hey, I made a little port of this to PAL SMB: https://github.com/threecreepio/pallsson since I was testing some things out there, and I missed having your rom for it..

No issues just figured I'd let you know in case you want me to get rid of it or anything!

I don't expect it'll be used by more than a couple of people, the PAL SMB community is pretty nonexistent.

**Comment by pellsson** [comment]
Lol no I love it :) The name is brilliant lol :)

Will make sure to put a link to it from the main page.

**Comment by threecreepio** [comment]
Oh man, exposure!

Hehe thanks man, and thanks for the great work on the practice rom!
