### ISSUE TITLE
Font selection doesnt work

### ISSUE THREAD

**Issue by pellsson** [pellsson/smb#45]
Just use the next CHR-BANK if a different font is requested...

**Comment by threecreepio** [comment]
Something I was thinking about if we're using CHR-ROM was swapping CHR bank from start of frame until SPR0 hit to a status bar bank. That way we could have proper graphics for the input display, and switchable fonts would be pretty easy?

**Comment by pellsson** [comment]
Its an absolutely gourgeos solution and I love the idea; however
considering we have close to 9 petabyte worth of chrrom, do we gain
anything from just redundantly selecting it based on wram preference on
startup?

**Comment by threecreepio** [comment]
Fair, we could just select the smb1 or smb2j CHR during the status bar rendering, if we use the same SPR0 tile on both.

**Comment by pellsson** [comment]
Ah, is spr0 not the same 0xff index in both CHRs? I am a bit drunk and
everone around me is speaking stockholmska which is severely compromising
my cognitive ability. Especially the last part.

**Comment by pellsson** [comment]
Hmmm think we confused SPR with BG banks? This was really easy in the end hehe. Might have misunderstood something though ;)

**Comment by threecreepio** [comment]
oh right yeah, haha. brain doesn't work so great.
