### ISSUE TITLE
Trying to get in contact about some collaboration

### ISSUE THREAD

**Issue by Squeemos** [pellsson/smb#49]
I'm not sure how else to do this since it doesn't seem that you have an active twitter, but I was wondering if you had some time to talk about how you are able to change levels for the game? I'm trying to work on a project for SMBJ2, and one of the current hiccups is that we don't know a method to "start" the game at like 4-1

**Comment by pellsson** [comment]
It depends on what you are trying to do, and how you are modifying the game. With the risk of sounding a bit condesending, if you have to ask it is unlikely that my answer will help.

Maybe if you expand on what you are trying to do I could understand the scope better.

**Comment by Squeemos** [comment]
I guess the better way to explain it would be that we have a vanilla rom of the game. I'm wondering if there's a way to manipulate the memory to allow us to trick the game into loading say 4-1 instead of 1-1 at start, and being able to do this for all levels (excluding the puzzle levels for now)

I'm not sure if you're able to help out pointing me in a right direction for being able to do this, but I'm more than happy to provide as much as I can

**Comment by pellsson** [comment]
Just change the Level- and WorldNumber as you se fit. The code for it is in this very repo. Not sure how to help you beyond that. If you mean that you want GameGenie-codes for the levels I think they are on speedrun.com

**Comment by Squeemos** [comment]
Do you think you could point me to the file that does this? For reference, this is for a python project where we have direct access to the ram

**Comment by pellsson** [comment]
I just did. Search this repo for what I just told you. Good luck with your project.

**Comment by Squeemos** [comment]
Hey so I did what you said (sorry if I sound dumb) but we're encountering some problems when loading stages 5+ with it not getting the correct area. For example, 8-1 loads into the water section of the level rather than the start, but it does load 8-1. Are you aware of any thing that might cause this? I've been looking around your code but I can't seem to find anything on my own.

**Comment by pellsson** [comment]
Thank you for reaching out to the NESDEV clinic through this our main support channel. A closed issue is not closed until your satisfaction is garantueed, thats out motto.

Assuming you are working with the FDS worlds 5+ are not in RAM at start up, but must be banked in. Before you ask; you current support membership does not include banking, but luckily there is a wide wide wide selection of articles readily available online. Including but not limited to documentiation for the FDS.
